// <auto-generated />
using System;
using FolioMonitor.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolioMonitor.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250504003859_UpdateLatestSnapshotKeyLength")]
    partial class UpdateLatestSnapshotKeyLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FolioMonitor.Core.Models.Configuration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("FolioMonitor.Core.Models.FolioHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoSucursal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FolioActual")
                        .HasColumnType("int");

                    b.Property<int>("FolioFin")
                        .HasColumnType("int");

                    b.Property<int>("FolioInicio")
                        .HasColumnType("int");

                    b.Property<int>("FoliosDisponibles")
                        .HasColumnType("int");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Modulo", "Timestamp");

                    b.ToTable("FolioHistories");
                });

            modelBuilder.Entity("FolioMonitor.Core.Models.LatestFolioSnapshot", b =>
                {
                    b.Property<string>("CodigoSucursal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modulo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("FolioInicio")
                        .HasColumnType("int");

                    b.Property<int>("FolioFin")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FolioActual")
                        .HasColumnType("int");

                    b.Property<int>("FoliosDisponibles")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CodigoSucursal", "Modulo", "FolioInicio", "FolioFin");

                    b.ToTable("LatestFolioSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
